spool dml.crm.txt
connect crm/crm
--------------------------------------------------------------------------------
-------------------------- Data Manipulation Language --------------------------
-------------------------------------- DML -------------------------------------
------------------------ SELECT, INSERT, UPDATE, DELETE ------------------------
---------------------------------- GRUPO ALUNO ---------------------------------
--------------------------------------------------------------------------------

-- TUTOR
insert into tb_tutor (id_tutor, tx_descricao) values (1,'M�e');
insert into tb_tutor (id_tutor, tx_descricao) values (2,'Pai');
insert into tb_tutor (id_tutor, tx_descricao) values (3,'Av�');
insert into tb_tutor (id_tutor, tx_descricao) values (4,'Av�');
insert into tb_tutor (id_tutor, tx_descricao) values (5,'Tio');
insert into tb_tutor (id_tutor, tx_descricao) values (6,'Tia');
insert into tb_tutor (id_tutor, tx_descricao) values (7,'Primo');
insert into tb_tutor (id_tutor, tx_descricao) values (8,'Prima');
insert into tb_tutor (id_tutor, tx_descricao) values (9,'Madrasta');
insert into tb_tutor (id_tutor, tx_descricao) values (10,'Padastro');

-- FILIACAO
insert into tb_filiacao (id_filiacao, tx_nome,in_sexo,id_tutor) values (sq_filiacao.nextval,'Luiza Pessoa de Carvalho','F',1);
insert into tb_filiacao (id_filiacao, tx_nome,in_sexo,id_tutor) values (sq_filiacao.nextval,'Esteval Gomes dos Santos','M',2);

--------------------------------------------------------------------------------
-------------------------- Data Manipulation Language --------------------------
-------------------------------------- DML -------------------------------------
------------------------ SELECT, INSERT, UPDATE, DELETE ------------------------
-------------------------------- GRUPO DOMICILIO -------------------------------
--------------------------------------------------------------------------------
--pais
--http://www.bcb.gov.br/rex/ftp/paises.txt
insert into tb_pais(id_pais, tx_pais,in_sigla2,in_sigla3) values(1058,'Brasil','BR','BRA');
insert into tb_pais(id_pais, tx_pais,in_sigla2,in_sigla3) values(1,'N�o Informado','NI','NID');

--regiao
insert into tb_regiao(id_regiao, tx_regiao) values(1,'N�o Informado');
insert into tb_regiao(id_regiao, tx_regiao) values(2,'Centro - Oeste');
insert into tb_regiao(id_regiao, tx_regiao) values(3,'Norte');
insert into tb_regiao(id_regiao, tx_regiao) values(4,'Nordeste');
insert into tb_regiao(id_regiao, tx_regiao) values(5,'Sudeste');
insert into tb_regiao(id_regiao, tx_regiao) values(6,'Sul');

--estado
--http://portal.saude.gov.br/portal/arquivos/pdf/politica_saude_180610.pdf
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (12,'AC','Acre',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (27,'AL','Alagoas',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (13,'AM','Amazonas',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (16,'AP','Amap�',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (29,'BA','Bahia',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (23,'CE','Cear�',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (53,'DF','Distrito Federal',1058,2);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (32,'ES','Esp�rito Santo',1058,5);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (52,'GO','Goi�s',1058,2);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (21,'MA','Maranh�o',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (31,'MG','Minas Gerais',1058,5);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (50,'MS','Mato Grosso do Sul',1058,2);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (51,'MT','Mato Grosso',1058,2);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (15,'PA','Par�',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (25,'PB','Para�ba',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (26,'PE','Pernambuco',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (22,'PI','Piau�',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (41,'PR','Paran�',1058,6);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (33,'RJ','Rio de Janeiro',1058,5);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (24,'RN','Rio Grande do Norte',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (11,'RO','Rond�nia',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (14,'RR','Roraima',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (43,'RS','Rio Grande do Sul',1058,6);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (42,'SC','Santa Catarina',1058,6);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (28,'SE','Sergipe',1058,4);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (35,'SP','S�o Paulo',1058,5);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (17,'TO','Tocantis',1058,3);
INSERT INTO tb_estado(id_estado,in_sigla2,tx_estado,id_pais,id_regiao) VALUES (1,'NI','N�o Informado',1058,1);

--cidades de sp
--http://www.ibge.gov.br/cidadesat/topwindow.htm?1
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Adamantina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Adolfo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Agua�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�guas da Prata', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�guas de Lind�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�guas de Santa B�rbara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�guas de S�o Pedro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Agudos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Alambari', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Alfredo Marcondes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Altair', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Altin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Alto Alegre', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Alum�nio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�lvares Florence', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�lvares Machado', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�lvaro de Carvalho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Alvinl�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Americana', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Am�rico Brasiliense', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Am�rico de Campos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Amparo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Anal�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Andradina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Angatuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Anhembi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Anhumas', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Aparecida', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Aparecida d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Apia�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ara�ariguama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ara�atuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ara�oiaba da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Aramina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Arandu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Arape�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Araraquara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Araras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Arco-�ris', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Arealva', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Areias', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Arei�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ariranha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Artur Nogueira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Aruj�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Asp�sia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Assis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Atibaia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Auriflama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ava�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Avanhandava', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Avar�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bady Bassitt', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Balbinos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'B�lsamo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bananal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bar�o de Antonina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barbosa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bariri', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barra Bonita', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barra do Chap�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barra do Turvo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barretos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barrinha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Barueri', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bastos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Batatais', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bauru', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bebedouro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bento de Abreu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bernardino de Campos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bertioga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bilac', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Birigui', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Biritiba-Mirim', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Boa Esperan�a do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bocaina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bofete', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Boituva', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bom Jesus dos Perd�es', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bom Sucesso de Itarar�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bor�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Borac�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Borborema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Borebi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Botucatu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bragan�a Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Bra�na', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Brejo Alegre', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Brodowski', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Brotas', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Buri', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Buritama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Buritizal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cabr�lia Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cabre�va', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ca�apava', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cachoeira Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Caconde', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cafel�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Caiabu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Caieiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Caiu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cajamar', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cajati', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cajobi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cajuru', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Campina do Monte Alegre', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Campinas', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Campo Limpo Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Campos do Jord�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Campos Novos Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Canan�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Canas', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'C�ndido Mota', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'C�ndido Rodrigues', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Canitar', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cap�o Bonito', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Capela do Alto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Capivari', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Caraguatatuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Carapicu�ba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cardoso', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Casa Branca', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'C�ssia dos Coqueiros', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Castilho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Catanduva', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Catigu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cedral', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cerqueira C�sar', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cerquilho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ces�rio Lange', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Charqueada', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Chavantes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Clementina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Colina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Col�mbia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Conchal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Conchas', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cordeir�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Coroados', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Coronel Macedo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Corumbata�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cosm�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cosmorama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cotia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cravinhos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cristais Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cruz�lia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cruzeiro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cubat�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Cunha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Descalvado', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Diadema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dirce Reis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Divinol�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dobrada', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dois C�rregos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dolcin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dourado', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dracena', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Duartina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Dumont', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Echapor�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Eldorado', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Elias Fausto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Elisi�rio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Emba�ba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Embu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Embu-Gua�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Emilian�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Engenheiro Coelho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Esp�rito Santo do Pinhal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Esp�rito Santo do Turvo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Estiva Gerbi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Estrela d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Estrela do Norte', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Euclides da Cunha Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Fartura', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Fernando Prestes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Fernand�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Fern�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ferraz de Vasconcelos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Flora Rica', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Floreal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Fl�rida Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Flor�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Franca', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Francisco Morato', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Franco da Rocha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Gabriel Monteiro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'G�lia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Gar�a', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Gast�o Vidigal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Gavi�o Peixoto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'General Salgado', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Getulina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Glic�rio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guai�ara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guaimb�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Gua�ra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guapia�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guapiara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guar�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guara�a�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guaraci', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guarani d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guarant�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guararapes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guararema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guaratinguet�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guare�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guariba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guaruj�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guarulhos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guatapar�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Guzol�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Hercul�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Holambra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Hortol�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iacanga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iacri', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iaras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ibat�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ibir�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ibirarema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ibitinga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ibi�na', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ic�m', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iep�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Igara�u do Tiet�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Igarapava', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Igarat�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iguape', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ilha Comprida', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ilha Solteira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ilhabela', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Indaiatuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Indiana', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Indiapor�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'In�bia Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ipaussu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iper�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ipe�na', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ipigu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iporanga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ipu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Iracem�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Irapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Irapuru', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itaber�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ita�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itajobi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itaju', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itanha�m', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ita�ca', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapecerica da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapetininga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapeva', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapevi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapirapu� Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'It�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itaporanga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itapura', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itaquaquecetuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itarar�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itariri', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itatiba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itatinga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itirapina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itirapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itobi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Itupeva', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ituverava', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jaborandi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jaboticabal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jacare�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jaci', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jacupiranga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jaguari�na', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jales', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jambeiro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jandira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jardin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jarinu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ja�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jeriquara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Joan�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jo�o Ramalho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jos� Bonif�cio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'J�lio Mesquita', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jumirim', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Jundia�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Junqueir�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Juqui�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Juquitiba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lagoinha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Laranjal Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lav�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lavrinhas', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Leme', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Len��is Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Limeira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lind�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lins', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lorena', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lourdes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Louveira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Luc�lia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lucian�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lu�s Ant�nio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Luizi�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lup�rcio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Lut�cia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Macatuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Macaubal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Maced�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Magda', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mairinque', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mairipor�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Manduri', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Marab� Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Maraca�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Marapoama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mari�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mar�lia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Marin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Martin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mat�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mau�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mendon�a', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Meridiano', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mes�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Miguel�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mineiros do Tiet�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mira Estrela', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Miracatu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mirand�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mirante do Paranapanema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mirassol', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mirassol�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mococa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mogi das Cruzes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mogi Gua�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Moji Mirim', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mombuca', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mon��es', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Mongagu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monte Alegre do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monte Alto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monte Apraz�vel', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monte Azul Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monte Castelo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monte Mor', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Monteiro Lobato', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Morro Agudo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Morungaba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Motuca', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Murutinga do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nantes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Narandiba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Natividade da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nazar� Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Neves Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nhandeara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nipo�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Alian�a', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Campina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Cana� Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Castilho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Europa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Granada', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Guataporanga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Independ�ncia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Luzit�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nova Odessa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Novais', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Novo Horizonte', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Nuporanga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ocau�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, '�leo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ol�mpia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Onda Verde', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Oriente', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Orindi�va', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Orl�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Osasco', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Oscar Bressane', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Osvaldo Cruz', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ourinhos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ouro Verde', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ouroeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pacaembu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Palestina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Palmares Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Palmeira d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Palmital', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Panorama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paragua�u Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paraibuna', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Para�so', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paranapanema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paranapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Parapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pardinho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pariquera-A�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Parisi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Patroc�nio Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paulic�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (353650, 'Paul�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paulist�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Paulo de Faria', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pederneiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pedra Bela', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pedran�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pedregulho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pedreira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pedrinhas Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pedro de Toledo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pen�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pereira Barreto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pereiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Peru�be', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piacatu', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piedade', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pilar do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pindamonhangaba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pindorama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pinhalzinho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piquerobi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piquete', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piracaia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piracicaba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piraju', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piraju�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pirangi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pirapora do Bom Jesus', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pirapozinho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pirassununga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Piratininga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pitangueiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Planalto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Platina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Po�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Poloni', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pomp�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ponga�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pontal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pontalinda', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pontes Gestal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Populina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Porangaba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Porto Feliz', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Porto Ferreira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Potim', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Potirendaba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Pracinha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Prad�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Praia Grande', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Prat�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Presidente Alves', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Presidente Bernardes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Presidente Epit�cio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Presidente Prudente', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Presidente Venceslau', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Promiss�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Quadra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Quat�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Queiroz', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Queluz', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Quintana', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rafard', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rancharia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Reden��o da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Regente Feij�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Regin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Registro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Restinga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o Bonito', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o Branco', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o Corrente', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o dos �ndios', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o Grande', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o Pires', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ribeir�o Preto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rifaina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rinc�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rin�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rio Claro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rio das Pedras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rio Grande da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Riol�ndia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Riversul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rosana', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Roseira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rubi�cea', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Rubin�ia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sabino', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sagres', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sales', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sales Oliveira', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sales�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Salmour�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Saltinho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Salto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Salto de Pirapora', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Salto Grande', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sandovalina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Ad�lia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Albertina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa B�rbara d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Branca', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Clara d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Cruz da Concei��o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Cruz da Esperan�a', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Cruz das Palmeiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Cruz do Rio Pardo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Ernestina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa F� do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Gertrudes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Isabel', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa L�cia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Maria da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Mercedes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Rita d`Oeste', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Rita do Passa Quatro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Rosa de Viterbo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santa Salete', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santana da Ponte Pensa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santana de Parna�ba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Anast�cio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Andr�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Ant�nio da Alegria', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Ant�nio de Posse', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Ant�nio do Aracangu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Ant�nio do Jardim', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Ant�nio do Pinhal', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santo Expedito', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sant�polis do Aguape�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Santos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Bento do Sapuca�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Bernardo do Campo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Caetano do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Carlos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Francisco', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jo�o da Boa Vista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jo�o das Duas Pontes', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jo�o de Iracema', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jo�o do Pau d`Alho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Joaquim da Barra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jos� da Bela Vista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jos� do Barreiro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jos� do Rio Pardo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jos� do Rio Preto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Jos� dos Campos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Louren�o da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Lu�s do Paraitinga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Manuel', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Miguel Arcanjo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355030, 'S�o Paulo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Pedro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Pedro do Turvo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Roque', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Sebasti�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Sebasti�o da Grama', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Sim�o', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'S�o Vicente', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sarapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sarutai�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sebastian�polis do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Serra Azul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Serra Negra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Serrana', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sert�ozinho', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sete Barras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sever�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Silveiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Socorro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sorocaba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sud Mennucci', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Sumar�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Suzan�polis', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Suzano', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tabapu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tabatinga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tabo�o da Serra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taciba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tagua�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taia�u', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tai�va', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tamba�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tanabi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tapira�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tapiratiba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taquaral', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taquaritinga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taquarituba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taquariva�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tarabai', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tarum�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tatu�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Taubat�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tejup�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Teodoro Sampaio', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Terra Roxa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tiet�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Timburi', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Torre de Pedra', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Torrinha', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Trabiju', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Trememb�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tr�s Fronteiras', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tuiuti', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tup�', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Tupi Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Turi�ba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Turmalina', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ubarana', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ubatuba', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ubirajara', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Uchoa', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Uni�o Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Ur�nia', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Uru', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Urup�s', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Valentim Gentil', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Valinhos', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Valpara�so', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Vargem', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Vargem Grande do Sul', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'Vargem Grande Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (sq_cidade.nextval, 'V�rzea Paulista', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355660, 'Vera Cruz', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355670, 'Vinhedo', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355680, 'Viradouro', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355690, 'Vista Alegre do Alto', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355695, 'Vit�ria Brasil', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355700, 'Votorantim', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355710, 'Votuporanga', 26);
insert into tb_cidade (id_cidade, tx_cidade,id_estado) values (355715, 'Zacarias', 26);


--http://www.paulinia.sp.gov.br/downloads.aspx
--bairro e logradouros
commit;
spool off
exit